[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['huffmate/=lib/huffmate/', 'foundry-huff/=lib/foundry-huff/']

[fmt]
bracket_spacing = true
multiline_func_header = "all"
number_underscore = "thousands"
wrap_comments = true

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
polygon_mumbai = "${MUMBAI_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config